### PR TITLE
Docs for TAG names best pratices

### PR DESCRIPTION
**Pull request by Grohden**
I added a simple description about what we discussed in #47 
i also added Kotlin syntax highlight and changed the code examples to follow the recommendation

### CODE REVIEW

**Comment by Grohden** [comment]
@levibostian nice bot XD, but we really need to change versions for readme/best practices docs?

**Comment by Grohden** [comment]
Oh, i forgot to mention.. i do think that `TAG` is kind of a confusing name, i'm used to use `simpleName` as `TAG` for my android logs, i know this is probably borrowed from the schedule lib, but i would use `IDENTIFIER` or `TASK_IDENTIFIER` as a param name.. but this is also confusing as we have `dataId` and `groupId` as "task identifier".. not sure if there's a better solution, `TASK_MAP_IDENTIFIER` or something similar seems too verbose for me..

**Comment by levibostian** [comment]
This is fantastic. Great detail, but yet to the point. Awesome job on the docs. 

Before this gets merged, we should also probably update the example app to match these new best practices. 

Could you, please, edit the example app [pending task](https://github.com/levibostian/Wendy-Android/blob/master/app/src/main/java/com/levibostian/wendyexample/FooPendingTask.kt) and [the factory](https://github.com/levibostian/Wendy-Android/blob/master/app/src/main/java/com/levibostian/wendyexample/WendyExamplePendingTasksFactory.kt#L11)? I'm not sure if anything else needs done to get the example app to compile and run. 

---

Don't worry about changing the changelog or version name as the bot suggested. I need to make an edits to the `Dangerfile` and repo config to do what I want it to do. I don't like to merge everything into `master` if I can help it. That's why the bot exists.

**Comment by levibostian** [comment]
@Grohden about your [comment](https://github.com/levibostian/Wendy-Android/pull/49#issuecomment-445406275) on the use of `TAG`. 

I see the pros and cons of using `TAG` as....

Pros: 
* Unique name that is not too similar to the other identifiers so it's not too difficult to getting them confused. 
* Not using the name `description` as Swift reserves that property name and I want Wendy-Android and Wendy-iOS's APIs to match for the most part. 
* Tag is a common pattern I have seen in other projects that are like Wendy such as [android-job](https://github.com/evernote/android-job) and [WorkManager](https://developer.android.com/reference/androidx/work/WorkManager#getWorkInfosByTag(java.lang.String)). 

Cons:
* I do agree with you. It could be more descriptive into what it is used for to improve the API. You wouldn't understand the purpose of it unless you looked at the docs. 

If you have more you would like to discuss on the topic, open up an issue and it can be opened for discussion.

**Comment by levibostian** [comment]
Thanks a ton for the PR, @Grohden. You rock 👍🥇!

**Comment by Grohden** [comment]
Oh, didn't looked at the example app, i'll update it

--------

Is always good help a project that helped me a lot XD (and by a lot i mean A LOT hehe)

**Comment by levibostian** [comment]
@Grohden great, thank you for updating that. 

I created a note to myself to create more github issues talking about plans I have for this project to making it a better library for others to use. 

I very much appreciate you using it and commenting on the project so far. From you using it, your comments would be very valuable. 

I created Wendy and [Teller](https://github.com/levibostian/teller-android/) (warning: the Teller-Android API is changing soon as I finish some big changes on [Teller-iOS](https://github.com/levibostian/teller-ios)) this year as 2 tools to help me **tons** in all of my apps that I build. I am glad that Wendy has helped you too!

**Comment by Grohden** [comment]
Done

**Comment by levibostian** [comment]
Thank you for the PR, @Grohden. I appreciate this! 

Check out [issues for the next milestone](https://github.com/levibostian/Wendy-Android/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A0.3.0-alpha) `0.3.0-alpha` or comment on [future issues that need more discussion](https://github.com/levibostian/Wendy-Android/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Needs+more+discussion%22). 

Thanks!

**Pull request merged**
